# Generated by Django 6.0.5 on 2026-05-29 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='inscripciones.inscripcion'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
